apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: apps
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    replicaCount: 2
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3